'''
This file contains the functions necessary for the implementation of the hangman game,
which should be able to run within each channel of the slackr
'''
import random
import pickle
import string
from state import get_store

word_file = "/usr/share/dict/words"
with open(word_file) as FILE:   
    WORDS = FILE.read().splitlines()
MAX_LIVES = 10

def generate_word():
    '''
    Generates a random word from /usr/share/dict/words
    that is 10 letters long or less, and returns it.
    '''
    word = random.choice(WORDS)
    while len(word) > 10:
        word = random.choice(WORDS)
    
    return list(word.upper())

def start_game(channel_id):
    '''
    Creates a temporary database in which to store the word to guess,
    and the letters of the alphabet as well as whether each letter has been guessed.
    Unique to each channel; assuming only one game per channel at a time.
    Turns on hangman mode in state.py
    '''
    data = get_store().channels.get_hangman(channel_id)
    data = {
        "target_word": generate_word(),
        "user_guess": ['?' for letter in target_word],
        "letters_guessed": dict.fromkeys(string.ascii_uppercase, False), 
        # dictionary with alphabet letters as keys and values default to False
        "lives_remaining": MAX_LIVES,
        "game_end": False,
        "output": "\n HANGMAN BOT:\n Let's play Hangman! Type /quit to quit the game."
    }

    assert len(data['user_guess']) == len(data['target_word'])

    return data

def guess(letter, channel_id, name_first):
    '''
    Inputs: letter guessed by the user, target_word (list) generated by the backend

    When the user guesses whether a letter is in the word,
    inform the user that:
    a. the guess is correct
    b. the guess is incorrect
    c. the guess is invalid (not alpha or not single char)
    '''
    data = get_store().channels.get_hangman(channel_id)
    data['output'] = "\nHANGMAN BOT: \n"

    # input invalid
    if len(letter) == 0 or len(letter) > 1 or letter.isalpha() is False:
        data['output'] += "Please try again. Enter only a single letter: "

    # letter already guessed
    elif data['letters_guessed'][letter.upper()] is True:
        data['output'] += "This letter has already been guessed, please enter another letter: "

    # correct guess
    elif letter in data['target_word']:
        data['letters_guessed'][letter.upper()] = True

        i = 0
        while i < len(data['target_word']):
            if data['target_word'][i] == letter.upper():
                data['user_guess'][i] = letter.upper()

        data['output'] += "That's right!\n" + ' '.join(data['user_guess'])

        if '?' not in data['user_guess']:
            data['game_end'] = True
            data['output'] += f"\n Congratulations {name_first}! You win!"

    # incorrect guess
    else:
        data['letters_guessed'][letter.upper()] = True
        data['lives_remaining'] -= 1
        data['output'] += f"That's wrong, you have {data['lives_remaining']} lives remaining."
        if data['lives_remaining'] == 0:
            data['output'] += "\n You lose! :("
            data['game_end'] = True

    return data 